[book]
authors = ["Mikko Murto"]
language = "en"
multilingual = false
src = "src"
title = "Double Open"

[build]
create-missing = true

[output.html]
git-repository-url = "https://github.com/doubleopen-project/doubleopen-project.github.io"